vich_uploader:
    db_driver: orm


    mappings:
        recette_image:
            uri_prefix : /images/recettes
            upload_destination : '%kernel.project_dir%/public/images/recettes' 
            namer : Vich\UploaderBundle\Naming\UniqidNamer
        # variable de configuration. Recupere le repertoire
        # Lors d'un DL, il récupère le fichier et l'enregistre dans le dossier "images" 
        # qui sera créé lors de la création d'un fichier

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
